apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-certificate
  namespace: {{ .Values.app.namespace }}
spec:
  secretName: {{ .Values.app.name }}-tls
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  dnsNames:
    - {{ .Values.ingress.host }}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuerName }}
    kind: ClusterIssuer