services:
  db:
    image: postgres:17
    container_name: Fact-Boi-Database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - fact_boi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  fact_boi_postgres_data:
