apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secret
  namespace: ${NAMESPACE}
stringData:
  DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-service.${POSTGRES_NAMESPACE}.svc.cluster.local:5432/${POSTGRES_DATABASE}"
  AUTH_SECRET: "${AUTH_SECRET}"