apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-deployment
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: {{ .Values.app.name }}-create-database
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        command: ["sh", "-c", "bun create-database.ts"]
        envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          - secretRef:
              name: {{ .Values.app.name }}-secret
      - name: {{ .Values.app.name }}-migrate
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        command: ["sh", "-c", "bunx drizzle-kit push"]
        envFrom:
          - configMapRef:
              name: {{ .Values.app.name }}-config
          - secretRef:
              name: {{ .Values.app.name }}-secret
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.app.name }}-config
        - secretRef:
            name: {{ .Values.app.name }}-secret
