apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
stringData:
  DISCORD_TOKEN: {{ .Values.discord.token | quote }}
  CLIENT_ID: {{ .Values.discord.clientId | quote }}
  POSTGRES_USERNAME: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
