name: Deploy

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REPOSITORY: rutger505/fact-boi
  APP_NAME: fact-boi

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.config.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate build config
        id: config
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          
          echo "Setting tag to $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ steps.config.outputs.tag }}
          cache-from: type=registry,ref=${{ env.DOCKER_REPOSITORY }}:cache
          cache-to: type=registry,ref=${{ env.DOCKER_REPOSITORY }}:cache,mode=max

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs:
      - build-docker-image

    strategy:
      matrix:
        environment:
          - ${{ startsWith(github.ref, 'refs/tags/') && 'production' || format('pr-{0}', github.event.pull_request.number) }}

    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate deployment config
        id: config
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            LETSENCRYPT_ENV="production"
            POSTGRES_ENV="production"
          else
            LETSENCRYPT_ENV="staging"
            POSTGRES_ENV="test"
          fi
          
          echo "Setting letsencrypt_env to $LETSENCRYPT_ENV"
          echo "letsencrypt_env=$LETSENCRYPT_ENV" >> $GITHUB_OUTPUT
          
          echo "Setting postgres_env to $POSTGRES_ENV"
          echo "postgres_env=$POSTGRES_ENV" >> $GITHUB_OUTPUT
          
          NAMESPACE=$APP_NAME-${{ matrix.environment }}
          echo "Setting namespace to $NAMESPACE"
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.16.2'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'

      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Process values file with envsubst
        env:
          APP_NAME: ${{ env.APP_NAME }}
          APP_ENV: ${{ matrix.environment }}
          DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
          DOCKER_TAG: ${{ needs.build-docker-image.outputs.tag }}
          POSTGRES_ENV: ${{ steps.config.outputs.postgres_env }}
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          envsubst < ./k8s/values.yaml > ./k8s/processed-values.yaml

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install  \
            ${{ env.APP_NAME }}-${{ matrix.environment }}  \
            ./k8s \
            -f ./k8s/processed-values.yaml \
            --namespace ${{ steps.config.outputs.namespace }} \
            --create-namespace \
            --wait \
            --timeout 1m \
            --atomic
